export const AUTH_REGISTER = 'AUTH_REGISTER';
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_RESET = 'AUTH_RESET';
export const AUTH_DELETE = 'AUTH_DELETE';
export const AUTH_LOADING = 'AUTH_LOADING';
export const AUTH_STATUS_TITLE = 'AUTH_STATUS_TITLE';
export const AUTH_STATUS_EMAIL = 'AUTH_STATUS_EMAIL';
export const AUTH_STATUS_PASSWORD = 'AUTH_STATUS_PASSWORD';

export const MODAL_AUTH_TOGGLE = 'MODAL_AUTH_TOGGLE';
export const MODAL_REGISTRATION_TOGGLE = 'MODAL_REGISTRATION_TOGGLE';
export const MODAL_FORGOT_TOGGLE = 'MODAL_FORGOT_TOGGLE';
export const MODAL_SERVICE_TOGGLE = 'MODAL_SERVICE_TOGGLE';
export const MODAL_SERVICE_EDIT_TOGGLE = 'MODAL_SERVICE_EDIT_TOGGLE';

export const PROFILE_SET_LOADING = 'PROFILE_SET_LOADING'; 
export const PROFILE_GET_OWN = 'PROFILE_GET_OWN'; 
export const PROFILE_CHANGE_OWN = 'PROFILE_CHANGE_OWN'; 
export const PROFILE_GET_ANOTHER = 'PROFILE_GET_ANOTHER'; 
export const PROFILE_GET_ALL = 'PROFILE_GET_ALL'; 
export const PROFILE_SET_STATUS = 'PROFILE_SET_STATUS'; 

export const SERVICE_CREATE = 'SERVICE_CREATE';
export const SERVICE_GET_USER = 'SERVICE_GET_USER';
export const SERVICE_GET_ALL = 'SERVICE_GET_ALL';
export const SERVICE_GET_ONE = 'SERVICE_GET_ONE';
export const SERVICE_CHENGE = 'SERVICE_CHENGE';
export const SERVICE_DELETE = 'SERVICE_DELETE';
